// import type { Metadata } from "next";
// import localFont from "next/font/local";
// // import "@/app/assets/styles/globals.css";
// import Providers from "./providers/Providers";
// import { useContext } from "react";
// import { ThemeContext } from "./providers/theme-provider";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const {theme} = useContext(ThemeContext)
//   return (
//     <html lang="en">
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased ${theme}`}
//         >
//           {/* <Providers> */}
//               {children}
//           {/* </Providers> */}
//         </body>

//     </html>
//   );
// }
